site_name: Alex Zhao's Public Pages

nav:
  - Home: index.md
  - Crypto:
    - ZK Notes: Material Knowledge/Sciences/Coding/Crypto/Proving Systems (Plonky3, Halo2, Circle STARKs, Binius).md
  - Coding:
    - Vim Tricks: Material Knowledge/Sciences/Coding/Vim Tricks.md
    - USACO Notes: Material Knowledge/Sciences/Coding/USACO/General Thoughts, Paradigms.md
  - Food and Cooking:
    - 糖醋排骨: 糖醋排骨.md